const userData = [
    {
        id: 1,
        name: 'John Doe',
        username: 'john_doe',
        email: 'john@example.com',
        imageUrl: 'https://via.placeholder.com/150',
        location: {
            city: 'New York',
            state: 'NY',
            country: 'USA',
        },
        successRate: 85,
        status: 'active',
    },
    {
        id: 2,
        name: 'Jane Smith',
        username: 'jane_smith',
        email: 'jane@example.com',
        imageUrl: 'https://via.placeholder.com/150',
        location: {
            city: 'Los Angeles',
            state: 'CA',
            country: 'USA',
        },
        successRate: 92,
        status: 'pending',
    },
    {
        id: 3,
        name: 'Bob Johnson',
        username: 'bob_johnson',
        email: 'bob@example.com',
        imageUrl: 'https://via.placeholder.com/150',
        location: {
            city: 'Chicago',
            state: 'IL',
            country: 'USA',
        },
        successRate: 78,
        status: 'disabled',
    },
    {
        id: 4,
        name: 'Alice Davis',
        username: 'alice_davis',
        email: 'alice@example.com',
        imageUrl: 'https://via.placeholder.com/150',
        location: {
            city: 'London',
            country: 'UK',
        },
        successRate: 90,
        status: 'active',
    },
    {
        id: 5,
        name: 'Charlie Brown',
        username: 'charlie_brown',
        email: 'charlie@example.com',
        imageUrl: 'https://via.placeholder.com/150',
        location: {
            city: 'Sydney',
            country: 'Australia',
        },
        successRate: 88,
        status: 'pending',
    },
    {
        id: 6,
        name: 'Eva Martinez',
        username: 'eva_martinez',
        email: 'eva@example.com',
        imageUrl: 'https://via.placeholder.com/150',
        location: {
            city: 'Barcelona',
            country: 'Spain',
        },
        successRate: 95,
        status: 'active',
    },
    {
        id: 7,
        name: 'Michael Wang',
        username: 'michael_wang',
        email: 'michael@example.com',
        imageUrl: 'https://via.placeholder.com/150',
        location: {
            city: 'Beijing',
            country: 'China',
        },
        successRate: 87,
        status: 'disabled',
    },
    // Add more users as needed
];
